name: APP

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


jobs:
  build:
    name: Building our APP

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    
    - name: Install dependencies
      run: dotnet restore
    
    - name: Build
      run: dotnet build --configuration Release --no-restore
    
    - name: Test
      run: dotnet test --no-restore --verbosity normal
    
    - name: Publish
      run: dotnet publish -c Release -o publish

    - run: zip app.zip *
      working-directory: publish
      
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: 'build'
        path: publish/app.zip
  
  prod:
#https://docs.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions
#https://docs.github.com/en/actions/configuring-and-managing-workflows/using-environment-variables    
    name: Deploy Production Environment
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    
    steps:
      - name: Download the build
        uses: actions/download-artifact@v2
        with:
          name: 'build'
          
      - uses: azure/login@v1.1
        with:
         creds: ${{ secrets.AZURE_CREDENTIALS }}
          
      - name: get the publishing profile
        id: publish_profile
        run: |
         webappname=${{ github.repository_owner }}-prod-app
         text=$(az webapp deployment list-publishing-profiles --name  ${webappname} --resource-group 'prod-rg' --xml)
         
         text="${text//'%'/'%25'}"
         text="${text//$'\n'/'%0A'}"
         text="${text//$'\r'/'%0D'}"
         echo $text
         echo "::set-output name=xml::$text"
         
      - name: Deploy the build
        uses: azure/webapps-deploy@v2
        with: 
          app-name: ${{ github.repository_owner }}-prod-app
          #publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE  }} # Define secret variable in repository settings as per action documentation
          publish-profile: ${{ steps.publish_profile.outputs.xml }}
          package: 'app.zip'
    
