name: APP

defaults:
  run:
    shell: bash

on:
  push:
    branches: [ master ] 

jobs:
     
  build:
    name: CI (Build)
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    
    - name: Install dependencies
      run: dotnet restore
    
    - name: Build
      run: |
        dotnet build --configuration Release --no-restore
    
    - name: Test
      run: dotnet test --no-restore --verbosity normal
    
    - name: Publish
      run: dotnet publish -c Release -o publish

    - run: zip -r app.zip *
      working-directory: publish
      
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: 'build'
        path: publish/app.zip
  
  deploy_prod:
  #https://docs.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions
  #https://docs.github.com/en/actions/configuring-and-managing-workflows/using-environment-variables
    name: CD (Deploy Production Environment)
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    env:
      ENVIRONMENT: prod
    
    steps:
      - name: Download the build
        uses: actions/download-artifact@v2
        with:
          name: 'build'
          
      - uses: azure/login@v1.1
        with:
         creds: ${{ secrets.AZURE_CREDENTIALS }}         
         
      - name: Deploy the build
        uses: azure/webapps-deploy@v2
        with: 
          app-name: ${{ github.repository_owner }}-${{ env.ENVIRONMENT }}-app
          package: 'app.zip'
    
