name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
#     - uses: actions/checkout@v2

#     - name: Setup .NET Core
#       uses: actions/setup-dotnet@v1
#       with:
#         dotnet-version: 3.1.301

#     - name: Install dependencies
#       run: dotnet restore

#     - name: Build
#       run: dotnet build --configuration Release --no-restore --output release

#     - name: Test
#       run: dotnet test --no-restore --verbosity normal
      
    - uses: actions/checkout@v2
      with:
        repository: 'Azure/azure-quickstart-templates'
        path: 'azure-quickstart-templates'
        
        
    - name: Run ARM-TTK
      uses: venura9/arm-ttk@master
      id: arm-ttk
      with: 
        path: azure-quickstart-templates/101-webapp-basic-windows/

    - name: Results for Run ARM-TTK with 'path'
      run: |
        content=${{ steps.arm-ttk.outputs.results }}
        echo "Results $content"    
    



