name: .NET Core


on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

# https://github.com/actions/checkout      
    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301

    - name: Install dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore --output release

    - name: Test
      run: dotnet test --no-restore --verbosity normal


#     - uses: actions/checkout@v2
#       with:
#         repository: 'Azure/azure-quickstart-templates'
#         path: 'azure-quickstart-templates'
        
        
#     - name: Run ARM-TTK
#       uses: venura9/arm-ttk@master
#       id: arm-ttk
#       with: 
#         path: azure-quickstart-templates/101-webapp-basic-windows/

#     - name: Results for Run ARM-TTK with 'path'
#       run: |
#         content=${{ steps.arm-ttk.outputs.results }}
#         echo "Results $content"


# https://github.com/actions/create-release
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      with:
        tag_name: ${{ github.sha }}
        release_name: Release ${{ github.ref }} - $BUILD_NUMBER
        body: |
            Release ${{ github.ref }} - $BUILD_NUMBER
            Commig: ${{ github.sha }}
        draft: false
        prerelease: false
    



