#For a blank repo
#https://docs.github.com/en/actions/reference/workflow-commands-for-github-actions
#https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions
#set and get a variable
#jobs


name: .NET Core
#let's get a badge for the run
#https://docs.github.com/en/actions/reference/events-that-trigger-workflows
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

#https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions

jobs:
  build:

    runs-on: ubuntu-latest
#     defaults:
#       run:
#         shell: bash
#         working-directory: scripts


# marketplacce - https://github.com/marketplace?type=actions

# Checkout action - https://github.com/actions/checkout      
    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301

    - name: Install dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore --output release

    - name: Test
      run: dotnet test --no-restore --verbosity normal
    
    - run: zip build.zip *
      working-directory: release

#https://docs.github.com/en/actions/configuring-and-managing-workflows/persisting-workflow-data-using-artifacts
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: 'build'
        path: release/build.zip


    - uses: actions/checkout@v2
      with:
        repository: 'Azure/azure-quickstart-templates'
        path: 'azure-quickstart-templates'

#https://docs.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions
        
    - name: Run ARM-TTK
      uses: venura9/arm-ttk@master
      id: arm-ttk
      with: 
        path: azure-quickstart-templates/101-webapp-basic-windows/

    - name: Results for Run ARM-TTK with 'path'
      run: |
        content=${{ steps.arm-ttk.outputs.results }}
        echo "Results $content"

#https://github.com/marketplace/actions/azure-login
#    - uses: azure/login@v1.1
#      with:
#        creds: ${{ secrets.AZURE_CREDENTIALS }}



# https://github.com/actions/create-release

#     - name: Create Release
#       id: create_release
#       uses: actions/create-release@v1
#       env:
#         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
#       with:
#         tag_name: ${{ github.sha }}
#         release_name: Release ${{ github.ref }} - $BUILD_NUMBER
#         body: |
#             Release ${{ github.ref }} - $BUILD_NUMBER
#             Commig: ${{ github.sha }}
#         draft: false
#         prerelease: false

  prod:
#https://docs.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions
#https://docs.github.com/en/actions/configuring-and-managing-workflows/using-environment-variables    
    name: Deploy Production Environment
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'

    env:
      AZURE_WEBAPP_NAME: 'venura9-webapp-prod'
      WEBAPP_RG: 'venura9-webapp-prod-rg'
  
    steps:
      - name: Download the build
        uses: actions/download-artifact@v2
        with:
          name: 'build'

      - run: ls -al    

#https://github.com/marketplace/actions/azure-login



#https://github.com/marketplace/actions/azure-webapp
#https://github.com/Azure/actions-workflow-samples/blob/master/AppService/asp.net-core-webapp-on-azure.yml

#       # Deploy to Azure Web apps
#       - name: Deploy the build
#         uses: azure/webapps-deploy@v2
#         with: 
#           app-name: ${{ env.AZURE_WEBAPP_NAME }} # Replace with your app name
#           publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE  }} # Define secret variable in repository settings as per action documentation
#           package: 'build.zip'


