#For a blank repo
#https://docs.github.com/en/actions/reference/workflow-commands-for-github-actions
#https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions
#set and get a variable
#jobs


name: .NET Core
#let's get a badge for the run
#https://docs.github.com/en/actions/reference/events-that-trigger-workflows
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

#https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions

jobs:
  build:

    runs-on: ubuntu-latest
#     defaults:
#       run:
#         shell: bash
#         working-directory: scripts


# marketplacce - https://github.com/marketplace?type=actions

# Checkout action - https://github.com/actions/checkout      
    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301

    - name: Install dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore --output release

    - name: Test
      run: dotnet test --no-restore --verbosity normal
    
    - run: zip build.zip -r release


#     - uses: actions/checkout@v2
#       with:
#         repository: 'Azure/azure-quickstart-templates'
#         path: 'azure-quickstart-templates'

#https://docs.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions
#Literals and Functions 
        
#     - name: Run ARM-TTK
#       uses: venura9/arm-ttk@master
#       id: arm-ttk
#       with: 
#         path: azure-quickstart-templates/101-webapp-basic-windows/

#     - name: Results for Run ARM-TTK with 'path'
#       run: |
#         content=${{ steps.arm-ttk.outputs.results }}
#         echo "Results $content"


# https://github.com/actions/create-release

#     - name: Create Release
#       id: create_release
#       uses: actions/create-release@v1
#       env:
#         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
#       with:
#         tag_name: ${{ github.sha }}
#         release_name: Release ${{ github.ref }} - $BUILD_NUMBER
#         body: |
#             Release ${{ github.ref }} - $BUILD_NUMBER
#             Commig: ${{ github.sha }}
#         draft: false
#         prerelease: false

  dev:
#https://docs.github.com/en/actions/configuring-and-managing-workflows/using-environment-variables    
    name: Deploy Development Environment
    needs: build
    runs-on: ubuntu-latest
    env:
      WEBAPP: 'venura9-webapp-test'
      WEBAPP_RG: 'venura9-webapp-test-rg'
  
    steps:
      - name: Download math result for job 1
        uses: actions/download-artifact@v2
        with:
          name: 'build'




