name: Infrastructure
#let's get a badge for the run
#https://docs.github.com/en/actions/reference/events-that-trigger-workflows
on:
  push:
    branches: [ 'master' ]
  pull_request:
    branches: [ 'master' ]

#https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions

jobs:
  prod:

    runs-on: ubuntu-latest
    
    steps: 
    - uses: azure/login@v1
      with:
       creds: ${{ secrets.AZURE_CREDENTIALS }}
            
    - uses: actions/checkout@v2
      with:
        repository: 'Azure/azure-quickstart-templates'
        path: 'azure-quickstart-templates'
        
    - name: Run ARM-TTK
      uses: venura9/arm-ttk@master
      id: arm-ttk
      with: 
        path: azure-quickstart-templates/101-webapp-basic-windows/

    - name: Results for Run ARM-TTK with 'path'
      run: |
        content=${{ steps.arm-ttk.outputs.results }}
        echo "Results $content"
        
    # vaidate the syntax    
    - run: az group deployment validate --resource-group 'prod-rg' --template-file azuredeploy.json --parameters webAppName=${{ github.repository_owner }}-prod-app
      working-directory: azure-quickstart-templates/101-webapp-basic-windows/
    
    # compare the diff, read a bit more on what-if: https://docs.microsoft.com/en-us/azure/azure-resource-manager/templates/template-deploy-what-if?tabs=azure-powershell
    - run: az deployment group what-if --resource-group 'prod-rg' --template-file azuredeploy.json --parameters webAppName=${{ github.repository_owner }}-prod-app
      working-directory: azure-quickstart-templates/101-webapp-basic-windows/
    
    # deploy
    - run: az group deployment create --resource-group 'prod-rg' --template-file azuredeploy.json --parameters webAppName=${{ github.repository_owner }}-prod-app sku=B1
      working-directory: azure-quickstart-templates/101-webapp-basic-windows/
    
    
